/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EnvironmentsRouteImport } from './routes/environments'
import { Route as PRouteRouteImport } from './routes/p/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PIndexRouteImport } from './routes/p/index'
import { Route as PVirtualInstancesRouteImport } from './routes/p/virtual-instances'
import { Route as PPickListsRouteImport } from './routes/p/pick-lists'
import { Route as PExternalReferenceCodeRouteRouteImport } from './routes/p/$externalReferenceCode/route'
import { Route as PExternalReferenceCodeIndexRouteImport } from './routes/p/$externalReferenceCode/index'
import { Route as PQueryRestRouteImport } from './routes/p/query/rest'
import { Route as PQueryGraphqlRouteImport } from './routes/p/query/graphql'
import { Route as PMailingNotificationTemplatesRouteImport } from './routes/p/mailing/notification-templates'
import { Route as PMailingNotificationQueueRouteImport } from './routes/p/mailing/notification-queue'
import { Route as PExternalReferenceCodeSchemaRouteImport } from './routes/p/$externalReferenceCode/schema'
import { Route as PExternalReferenceCodeQueryRouteImport } from './routes/p/$externalReferenceCode/query'

const EnvironmentsRoute = EnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const PRouteRoute = PRouteRouteImport.update({
  id: '/p',
  path: '/p',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PIndexRoute = PIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PRouteRoute,
} as any)
const PVirtualInstancesRoute = PVirtualInstancesRouteImport.update({
  id: '/virtual-instances',
  path: '/virtual-instances',
  getParentRoute: () => PRouteRoute,
} as any)
const PPickListsRoute = PPickListsRouteImport.update({
  id: '/pick-lists',
  path: '/pick-lists',
  getParentRoute: () => PRouteRoute,
} as any)
const PExternalReferenceCodeRouteRoute =
  PExternalReferenceCodeRouteRouteImport.update({
    id: '/$externalReferenceCode',
    path: '/$externalReferenceCode',
    getParentRoute: () => PRouteRoute,
  } as any)
const PExternalReferenceCodeIndexRoute =
  PExternalReferenceCodeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PExternalReferenceCodeRouteRoute,
  } as any)
const PQueryRestRoute = PQueryRestRouteImport.update({
  id: '/query/rest',
  path: '/query/rest',
  getParentRoute: () => PRouteRoute,
} as any)
const PQueryGraphqlRoute = PQueryGraphqlRouteImport.update({
  id: '/query/graphql',
  path: '/query/graphql',
  getParentRoute: () => PRouteRoute,
} as any)
const PMailingNotificationTemplatesRoute =
  PMailingNotificationTemplatesRouteImport.update({
    id: '/mailing/notification-templates',
    path: '/mailing/notification-templates',
    getParentRoute: () => PRouteRoute,
  } as any)
const PMailingNotificationQueueRoute =
  PMailingNotificationQueueRouteImport.update({
    id: '/mailing/notification-queue',
    path: '/mailing/notification-queue',
    getParentRoute: () => PRouteRoute,
  } as any)
const PExternalReferenceCodeSchemaRoute =
  PExternalReferenceCodeSchemaRouteImport.update({
    id: '/schema',
    path: '/schema',
    getParentRoute: () => PExternalReferenceCodeRouteRoute,
  } as any)
const PExternalReferenceCodeQueryRoute =
  PExternalReferenceCodeQueryRouteImport.update({
    id: '/query',
    path: '/query',
    getParentRoute: () => PExternalReferenceCodeRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p': typeof PRouteRouteWithChildren
  '/environments': typeof EnvironmentsRoute
  '/p/$externalReferenceCode': typeof PExternalReferenceCodeRouteRouteWithChildren
  '/p/pick-lists': typeof PPickListsRoute
  '/p/virtual-instances': typeof PVirtualInstancesRoute
  '/p/': typeof PIndexRoute
  '/p/$externalReferenceCode/query': typeof PExternalReferenceCodeQueryRoute
  '/p/$externalReferenceCode/schema': typeof PExternalReferenceCodeSchemaRoute
  '/p/mailing/notification-queue': typeof PMailingNotificationQueueRoute
  '/p/mailing/notification-templates': typeof PMailingNotificationTemplatesRoute
  '/p/query/graphql': typeof PQueryGraphqlRoute
  '/p/query/rest': typeof PQueryRestRoute
  '/p/$externalReferenceCode/': typeof PExternalReferenceCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/environments': typeof EnvironmentsRoute
  '/p/pick-lists': typeof PPickListsRoute
  '/p/virtual-instances': typeof PVirtualInstancesRoute
  '/p': typeof PIndexRoute
  '/p/$externalReferenceCode/query': typeof PExternalReferenceCodeQueryRoute
  '/p/$externalReferenceCode/schema': typeof PExternalReferenceCodeSchemaRoute
  '/p/mailing/notification-queue': typeof PMailingNotificationQueueRoute
  '/p/mailing/notification-templates': typeof PMailingNotificationTemplatesRoute
  '/p/query/graphql': typeof PQueryGraphqlRoute
  '/p/query/rest': typeof PQueryRestRoute
  '/p/$externalReferenceCode': typeof PExternalReferenceCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p': typeof PRouteRouteWithChildren
  '/environments': typeof EnvironmentsRoute
  '/p/$externalReferenceCode': typeof PExternalReferenceCodeRouteRouteWithChildren
  '/p/pick-lists': typeof PPickListsRoute
  '/p/virtual-instances': typeof PVirtualInstancesRoute
  '/p/': typeof PIndexRoute
  '/p/$externalReferenceCode/query': typeof PExternalReferenceCodeQueryRoute
  '/p/$externalReferenceCode/schema': typeof PExternalReferenceCodeSchemaRoute
  '/p/mailing/notification-queue': typeof PMailingNotificationQueueRoute
  '/p/mailing/notification-templates': typeof PMailingNotificationTemplatesRoute
  '/p/query/graphql': typeof PQueryGraphqlRoute
  '/p/query/rest': typeof PQueryRestRoute
  '/p/$externalReferenceCode/': typeof PExternalReferenceCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/p'
    | '/environments'
    | '/p/$externalReferenceCode'
    | '/p/pick-lists'
    | '/p/virtual-instances'
    | '/p/'
    | '/p/$externalReferenceCode/query'
    | '/p/$externalReferenceCode/schema'
    | '/p/mailing/notification-queue'
    | '/p/mailing/notification-templates'
    | '/p/query/graphql'
    | '/p/query/rest'
    | '/p/$externalReferenceCode/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/environments'
    | '/p/pick-lists'
    | '/p/virtual-instances'
    | '/p'
    | '/p/$externalReferenceCode/query'
    | '/p/$externalReferenceCode/schema'
    | '/p/mailing/notification-queue'
    | '/p/mailing/notification-templates'
    | '/p/query/graphql'
    | '/p/query/rest'
    | '/p/$externalReferenceCode'
  id:
    | '__root__'
    | '/'
    | '/p'
    | '/environments'
    | '/p/$externalReferenceCode'
    | '/p/pick-lists'
    | '/p/virtual-instances'
    | '/p/'
    | '/p/$externalReferenceCode/query'
    | '/p/$externalReferenceCode/schema'
    | '/p/mailing/notification-queue'
    | '/p/mailing/notification-templates'
    | '/p/query/graphql'
    | '/p/query/rest'
    | '/p/$externalReferenceCode/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PRouteRoute: typeof PRouteRouteWithChildren
  EnvironmentsRoute: typeof EnvironmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/environments': {
      id: '/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof EnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p': {
      id: '/p'
      path: '/p'
      fullPath: '/p'
      preLoaderRoute: typeof PRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/': {
      id: '/p/'
      path: '/'
      fullPath: '/p/'
      preLoaderRoute: typeof PIndexRouteImport
      parentRoute: typeof PRouteRoute
    }
    '/p/virtual-instances': {
      id: '/p/virtual-instances'
      path: '/virtual-instances'
      fullPath: '/p/virtual-instances'
      preLoaderRoute: typeof PVirtualInstancesRouteImport
      parentRoute: typeof PRouteRoute
    }
    '/p/pick-lists': {
      id: '/p/pick-lists'
      path: '/pick-lists'
      fullPath: '/p/pick-lists'
      preLoaderRoute: typeof PPickListsRouteImport
      parentRoute: typeof PRouteRoute
    }
    '/p/$externalReferenceCode': {
      id: '/p/$externalReferenceCode'
      path: '/$externalReferenceCode'
      fullPath: '/p/$externalReferenceCode'
      preLoaderRoute: typeof PExternalReferenceCodeRouteRouteImport
      parentRoute: typeof PRouteRoute
    }
    '/p/$externalReferenceCode/': {
      id: '/p/$externalReferenceCode/'
      path: '/'
      fullPath: '/p/$externalReferenceCode/'
      preLoaderRoute: typeof PExternalReferenceCodeIndexRouteImport
      parentRoute: typeof PExternalReferenceCodeRouteRoute
    }
    '/p/query/rest': {
      id: '/p/query/rest'
      path: '/query/rest'
      fullPath: '/p/query/rest'
      preLoaderRoute: typeof PQueryRestRouteImport
      parentRoute: typeof PRouteRoute
    }
    '/p/query/graphql': {
      id: '/p/query/graphql'
      path: '/query/graphql'
      fullPath: '/p/query/graphql'
      preLoaderRoute: typeof PQueryGraphqlRouteImport
      parentRoute: typeof PRouteRoute
    }
    '/p/mailing/notification-templates': {
      id: '/p/mailing/notification-templates'
      path: '/mailing/notification-templates'
      fullPath: '/p/mailing/notification-templates'
      preLoaderRoute: typeof PMailingNotificationTemplatesRouteImport
      parentRoute: typeof PRouteRoute
    }
    '/p/mailing/notification-queue': {
      id: '/p/mailing/notification-queue'
      path: '/mailing/notification-queue'
      fullPath: '/p/mailing/notification-queue'
      preLoaderRoute: typeof PMailingNotificationQueueRouteImport
      parentRoute: typeof PRouteRoute
    }
    '/p/$externalReferenceCode/schema': {
      id: '/p/$externalReferenceCode/schema'
      path: '/schema'
      fullPath: '/p/$externalReferenceCode/schema'
      preLoaderRoute: typeof PExternalReferenceCodeSchemaRouteImport
      parentRoute: typeof PExternalReferenceCodeRouteRoute
    }
    '/p/$externalReferenceCode/query': {
      id: '/p/$externalReferenceCode/query'
      path: '/query'
      fullPath: '/p/$externalReferenceCode/query'
      preLoaderRoute: typeof PExternalReferenceCodeQueryRouteImport
      parentRoute: typeof PExternalReferenceCodeRouteRoute
    }
  }
}

interface PExternalReferenceCodeRouteRouteChildren {
  PExternalReferenceCodeQueryRoute: typeof PExternalReferenceCodeQueryRoute
  PExternalReferenceCodeSchemaRoute: typeof PExternalReferenceCodeSchemaRoute
  PExternalReferenceCodeIndexRoute: typeof PExternalReferenceCodeIndexRoute
}

const PExternalReferenceCodeRouteRouteChildren: PExternalReferenceCodeRouteRouteChildren =
  {
    PExternalReferenceCodeQueryRoute: PExternalReferenceCodeQueryRoute,
    PExternalReferenceCodeSchemaRoute: PExternalReferenceCodeSchemaRoute,
    PExternalReferenceCodeIndexRoute: PExternalReferenceCodeIndexRoute,
  }

const PExternalReferenceCodeRouteRouteWithChildren =
  PExternalReferenceCodeRouteRoute._addFileChildren(
    PExternalReferenceCodeRouteRouteChildren,
  )

interface PRouteRouteChildren {
  PExternalReferenceCodeRouteRoute: typeof PExternalReferenceCodeRouteRouteWithChildren
  PPickListsRoute: typeof PPickListsRoute
  PVirtualInstancesRoute: typeof PVirtualInstancesRoute
  PIndexRoute: typeof PIndexRoute
  PMailingNotificationQueueRoute: typeof PMailingNotificationQueueRoute
  PMailingNotificationTemplatesRoute: typeof PMailingNotificationTemplatesRoute
  PQueryGraphqlRoute: typeof PQueryGraphqlRoute
  PQueryRestRoute: typeof PQueryRestRoute
}

const PRouteRouteChildren: PRouteRouteChildren = {
  PExternalReferenceCodeRouteRoute:
    PExternalReferenceCodeRouteRouteWithChildren,
  PPickListsRoute: PPickListsRoute,
  PVirtualInstancesRoute: PVirtualInstancesRoute,
  PIndexRoute: PIndexRoute,
  PMailingNotificationQueueRoute: PMailingNotificationQueueRoute,
  PMailingNotificationTemplatesRoute: PMailingNotificationTemplatesRoute,
  PQueryGraphqlRoute: PQueryGraphqlRoute,
  PQueryRestRoute: PQueryRestRoute,
}

const PRouteRouteWithChildren =
  PRouteRoute._addFileChildren(PRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PRouteRoute: PRouteRouteWithChildren,
  EnvironmentsRoute: EnvironmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
